# Generated by Django 4.2.11 on 2024-05-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
